"""add pfx_password to empresa_fiscal_config

Revision ID: 2319efa6207a
Revises: 413fdfd1cd91
Create Date: 2026-02-25 21:14:41.150572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2319efa6207a'
down_revision = '413fdfd1cd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa_fiscal_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pfx_password', sa.String(length=255), nullable=False))
        batch_op.alter_column('cert_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('key_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa_fiscal_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.alter_column('cert_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('pfx_password')

    # ### end Alembic commands ###
