"""Agregar persona_autorizada_id a ventas

Revision ID: 2c73cb8c9403
Revises: a8e1ea4e60a0
Create Date: 2025-06-30 21:44:28.136827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c73cb8c9403'
down_revision = 'a8e1ea4e60a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona_autorizada_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'personas_autorizadas', ['persona_autorizada_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('persona_autorizada_id')

    # ### end Alembic commands ###
