"""Agregar saldo_favor a clientes

Revision ID: 332cf825f176
Revises: f1658604f4c5
Create Date: 2026-01-09 09:58:32.304281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332cf825f176'
down_revision = 'f1658604f4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_favor', sa.Numeric(precision=12, scale=2), nullable=True))

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('saldo')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('saldo_favor')

    # ### end Alembic commands ###
