"""Add nombre_archivo_excel to PlantillaImportacion

Revision ID: 36d8ca5d30ac
Revises: dc4b33ee0b32
Create Date: 2025-05-02 20:57:09.820792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d8ca5d30ac'
down_revision = 'dc4b33ee0b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas_importacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_archivo_excel', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas_importacion', schema=None) as batch_op:
        batch_op.drop_column('nombre_archivo_excel')

    # ### end Alembic commands ###
