"""agrega tipo_doc a clientes

Revision ID: 377dc2829fa5
Revises: 5374bf6eb980
Create Date: 2026-03-01 21:26:36.361551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377dc2829fa5'
down_revision = '5374bf6eb980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_doc', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('tipo_doc')

    # ### end Alembic commands ###
