"""Add nombre_corto to producto

Revision ID: 382a3618e01f
Revises: 8aada63bb56c
Create Date: 2025-05-03 11:00:36.237883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382a3618e01f'
down_revision = '8aada63bb56c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_corto', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('nombre_corto')

    # ### end Alembic commands ###
