"""Agregar campos presentacion_cantidad y es_fraccionable

Revision ID: 3bf9e84f177b
Revises: 97376c517e80
Create Date: 2025-06-09 21:03:44.450531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf9e84f177b'
down_revision = '97376c517e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presentacion_cantidad', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('es_fraccionable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('es_fraccionable')
        batch_op.drop_column('presentacion_cantidad')

    # ### end Alembic commands ###
