"""condicion iva fk

Revision ID: 413fdfd1cd91
Revises: 7ca036022159
Create Date: 2026-02-16 20:01:15.913265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413fdfd1cd91'
down_revision = '7ca036022159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condicion_iva_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'condiciones_iva', ['condicion_iva_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('condicion_iva_id')

    # ### end Alembic commands ###
