"""agregar fecha_emision a facturas

Revision ID: 443e28c7e0ad
Revises: 885239d7c274
Create Date: 2026-03-07 18:35:17.481593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443e28c7e0ad'
down_revision = '885239d7c274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_emision', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('punto_venta_emitido', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('numero_comprobante', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_column('numero_comprobante')
        batch_op.drop_column('punto_venta_emitido')
        batch_op.drop_column('fecha_emision')

    # ### end Alembic commands ###
