"""Add nombre_columna_nombre to plantilla_importacion

Revision ID: 48de849ca7e3
Revises: 382a3618e01f
Create Date: 2025-05-03 11:06:00.050267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48de849ca7e3'
down_revision = '382a3618e01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas_importacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_columna_nombre', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas_importacion', schema=None) as batch_op:
        batch_op.drop_column('nombre_columna_nombre')

    # ### end Alembic commands ###
