"""add letra to tipos_comprobante

Revision ID: 5374bf6eb980
Revises: d9489f4bf651
Create Date: 2026-03-01 20:56:15.129264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5374bf6eb980'
down_revision = 'd9489f4bf651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipos_comprobante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('letra', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipos_comprobante', schema=None) as batch_op:
        batch_op.drop_column('letra')

    # ### end Alembic commands ###
