"""cliente_id nullable en pagos

Revision ID: 711d5f674ec2
Revises: 443e28c7e0ad
Create Date: 2026-04-26 22:47:24.957086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711d5f674ec2'
down_revision = '443e28c7e0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'status', ['estado_id'], ['id'])
        batch_op.create_foreign_key(None, 'tipos_documento', ['tipo_documento_id'], ['id'])
        batch_op.create_foreign_key(None, 'condiciones_iva', ['condicion_iva_id'], ['id'])

    with op.batch_alter_table('condiciones_iva', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['codigo'])

    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['alias'])
        batch_op.create_unique_constraint(None, ['cbu'])
        batch_op.create_foreign_key(None, 'status', ['status_id'], ['id'])

    with op.batch_alter_table('detalle_pedido_proveedor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'pedidos_proveedor', ['pedido_id'], ['id'])
        batch_op.create_foreign_key(None, 'productos', ['producto_id'], ['id'])

    with op.batch_alter_table('detalles_venta', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'productos', ['producto_id'], ['id'])
        batch_op.create_foreign_key(None, 'ventas', ['venta_id'], ['id'])

    with op.batch_alter_table('empresa_fiscal_config', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cuit'])
        batch_op.create_foreign_key(None, 'condiciones_iva', ['condicion_iva_id'], ['id'])

    with op.batch_alter_table('factura_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'facturas', ['factura_id'], ['id'])
        batch_op.create_foreign_key(None, 'productos', ['producto_id'], ['id'])

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_comprobante_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tipos_comprobante', ['tipo_comprobante_id'], ['id'])
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])
        batch_op.create_foreign_key(None, 'puntos_venta', ['punto_venta_id'], ['id'])

    with op.batch_alter_table('imagenes_productos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'productos', ['producto_id'], ['id'])

    with op.batch_alter_table('marcas', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('movimientos_cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_cliente_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_cliente_tipo'), ['tipo'], unique=False)
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])
        batch_op.create_foreign_key(None, 'pagos', ['pago_id'], ['id'])
        batch_op.create_foreign_key(None, 'ventas', ['venta_id'], ['id'])

    with op.batch_alter_table('movimientos_cuenta', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cuentas', ['cuenta_destino_id'], ['id'])
        batch_op.create_foreign_key(None, 'cuentas', ['cuenta_id'], ['id'])
        batch_op.create_foreign_key(None, 'status', ['status_id'], ['id'])

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'formas_pago', ['forma_pago_id'], ['id'])
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])

    with op.batch_alter_table('pedidos_proveedor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'proveedores', ['proveedor_id'], ['id'])
        batch_op.create_foreign_key(None, 'status', ['estado_id'], ['id'])

    with op.batch_alter_table('personas_autorizadas', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])
        batch_op.create_foreign_key(None, 'status', ['estado_id'], ['id'])

    with op.batch_alter_table('plantillas_importacion', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['proveedor_id'])
        batch_op.create_foreign_key(None, 'proveedores', ['proveedor_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cod_interno'])
        batch_op.create_foreign_key(None, 'status', ['status_id'], ['id'])
        batch_op.create_foreign_key(None, 'unidades_medida', ['unidad_medida_id'], ['id'])
        batch_op.create_foreign_key(None, 'marcas', ['marca_id'], ['id'])
        batch_op.create_foreign_key(None, 'proveedores', ['proveedor_id'], ['id'])
        batch_op.create_foreign_key(None, 'categorias', ['categoria_id'], ['id'])

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['codigo_proveedor'])
        batch_op.create_unique_constraint(None, ['nombre'])
        batch_op.create_foreign_key(None, 'status', ['status_id'], ['id'])

    with op.batch_alter_table('puntos_venta', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_empresa_punto_venta', ['empresa_config_id', 'numero'])
        batch_op.create_foreign_key(None, 'empresa_fiscal_config', ['empresa_config_id'], ['id'])

    with op.batch_alter_table('resumenes_cuenta_corriente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumenes_cuenta_corriente_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resumenes_cuenta_corriente_status_id'), ['status_id'], unique=False)
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])
        batch_op.create_foreign_key(None, 'status', ['status_id'], ['id'])

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['code'])

    with op.batch_alter_table('tipos_comprobante', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['codigo_afip'])

    with op.batch_alter_table('tipos_documento', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['codigo_afip'])

    with op.batch_alter_table('unidades_medida', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['codigo'])
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'status', ['estado_id'], ['id'])

    with op.batch_alter_table('vendedores', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'proveedores', ['proveedor_id'], ['id'])

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'personas_autorizadas', ['persona_autorizada_id'], ['id'])
        batch_op.create_foreign_key(None, 'status', ['estado_id'], ['id'])
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['vendedor_id'], ['id'])
        batch_op.create_foreign_key(None, 'formas_pago', ['forma_pago_id'], ['id'])
        batch_op.create_foreign_key(None, 'facturas', ['factura_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('vendedores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('unidades_medida', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('tipos_documento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('tipos_comprobante', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('resumenes_cuenta_corriente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_resumenes_cuenta_corriente_status_id'))
        batch_op.drop_index(batch_op.f('ix_resumenes_cuenta_corriente_cliente_id'))

    with op.batch_alter_table('puntos_venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_empresa_punto_venta', type_='unique')

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('plantillas_importacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('personas_autorizadas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('pedidos_proveedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('movimientos_cuenta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('movimientos_cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_movimientos_cliente_tipo'))
        batch_op.drop_index(batch_op.f('ix_movimientos_cliente_cliente_id'))

    with op.batch_alter_table('marcas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('imagenes_productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipo_comprobante_id')

    with op.batch_alter_table('factura_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('empresa_fiscal_config', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('detalles_venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('detalle_pedido_proveedor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('condiciones_iva', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
