"""Agregar campo ubicacion_local a productos

Revision ID: 71dd166cf033
Revises: 453d904e394a
Create Date: 2025-05-03 19:47:28.700039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71dd166cf033'
down_revision = '453d904e394a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion_local', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('ubicacion_local')

    # ### end Alembic commands ###
