"""Agregar campo cuenta_corriente_activa a Cliente

Revision ID: 7ae897bb1db2
Revises: 3bf9e84f177b
Create Date: 2025-06-26 20:27:54.254737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae897bb1db2'
down_revision = '3bf9e84f177b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuenta_corriente_activa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('cuenta_corriente_activa')

    # ### end Alembic commands ###
