"""agrega modelo factura y relacion venta

Revision ID: 7ca036022159
Revises: 9d46cb4d5466
Create Date: 2026-02-16 11:31:51.119989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca036022159'
down_revision = '9d46cb4d5466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factura_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'facturas', ['factura_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('factura_id')

    # ### end Alembic commands ###
