"""agregar punto_venta_id a facturas

Revision ID: 885239d7c274
Revises: e35e7bcef2db
Create Date: 2026-03-07 18:00:58.936065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885239d7c274'
down_revision = 'e35e7bcef2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('punto_venta_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'puntos_venta', ['punto_venta_id'], ['id'])
        batch_op.drop_column('arca_punto_venta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arca_punto_venta', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('punto_venta_id')

    # ### end Alembic commands ###
