"""Agregar campo porcentaje_ganancia_personalizado a Producto

Revision ID: 8aada63bb56c
Revises: 36d8ca5d30ac
Create Date: 2025-05-03 09:02:48.734361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aada63bb56c'
down_revision = '36d8ca5d30ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('porcentaje_ganancia_personalizado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('porcentaje_ganancia_personalizado')

    # ### end Alembic commands ###
