"""Renombrar columna ultimo_uso a fecha_ultima_lista

Revision ID: 8dd72a510ed2
Revises: 71dd166cf033
Create Date: 2025-05-03 21:25:33.637656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8dd72a510ed2'
down_revision = '71dd166cf033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas_importacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_ultima_lista', sa.DateTime(), nullable=True))
        batch_op.drop_column('ultimo_uso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas_importacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_uso', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('fecha_ultima_lista')

    # ### end Alembic commands ###
