"""crear tabla puntos_venta y migrar datos

Revision ID: 90827fed111f
Revises: c5338be6f8d9
Create Date: 2026-03-03 13:07:40.353999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90827fed111f'
down_revision = 'c5338be6f8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa_fiscal_config', schema=None) as batch_op:
        batch_op.drop_column('punto_venta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa_fiscal_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('punto_venta', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
