"""Agrega unidades_por_presentacion a detalle pedido proveedor

Revision ID: 97376c517e80
Revises: 8e1014ed66c0
Create Date: 2025-05-22 22:40:17.039005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97376c517e80'
down_revision = '8e1014ed66c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_pedido_proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidades_por_presentacion', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_pedido_proveedor', schema=None) as batch_op:
        batch_op.drop_column('unidades_por_presentacion')

    # ### end Alembic commands ###
