"""Agregar porcentajede ganancia  en cada venta

Revision ID: 9d46cb4d5466
Revises: 332cf825f176
Create Date: 2026-02-12 21:31:50.540370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d46cb4d5466'
down_revision = '332cf825f176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('porcentaje_ganancia_aplicado', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_venta', schema=None) as batch_op:
        batch_op.drop_column('porcentaje_ganancia_aplicado')

    # ### end Alembic commands ###
