"""Agregar campo observaciones a ventas

Revision ID: a8e1ea4e60a0
Revises: 7ae897bb1db2
Create Date: 2025-06-27 10:57:52.146561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e1ea4e60a0'
down_revision = '7ae897bb1db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('observaciones')

    # ### end Alembic commands ###
