"""agregar columnas nuevas a PlantillaImportacion

Revision ID: bddc6c2dce1b
Revises: 2c73cb8c9403
Create Date: 2025-07-10 09:07:45.253969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bddc6c2dce1b'
down_revision = '2c73cb8c9403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas_importacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_columna_nombre_corto', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nombre_columna_ubicacion', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nombre_columna_unidad_medida', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nombre_columna_presentacion', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nombre_columna_es_fraccionable', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nombre_columna_porcentaje_ganancia', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nombre_columna_pg_personalizado', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas_importacion', schema=None) as batch_op:
        batch_op.drop_column('nombre_columna_pg_personalizado')
        batch_op.drop_column('nombre_columna_porcentaje_ganancia')
        batch_op.drop_column('nombre_columna_es_fraccionable')
        batch_op.drop_column('nombre_columna_presentacion')
        batch_op.drop_column('nombre_columna_unidad_medida')
        batch_op.drop_column('nombre_columna_ubicacion')
        batch_op.drop_column('nombre_columna_nombre_corto')

    # ### end Alembic commands ###
