"""Add cod_solo_numero to PlantillaImportacion

Revision ID: be780c46e420
Revises: 8dd72a510ed2
Create Date: 2025-05-04 10:32:47.442192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be780c46e420'
down_revision = '8dd72a510ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas_importacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_solo_numero', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas_importacion', schema=None) as batch_op:
        batch_op.drop_column('cod_solo_numero')

    # ### end Alembic commands ###
