"""Agregar campo codigo_afip a CondicionIVA

Revision ID: c5338be6f8d9
Revises: e24339f055be
Create Date: 2026-03-02 08:59:36.618562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5338be6f8d9'
down_revision = 'e24339f055be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condiciones_iva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_afip', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condiciones_iva', schema=None) as batch_op:
        batch_op.drop_column('codigo_afip')

    # ### end Alembic commands ###
