"""Renombrar cantidad a disponibles en productos

Revision ID: cf9544dab5f4
Revises: be780c46e420
Create Date: 2025-05-05 22:12:12.917501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9544dab5f4'
down_revision = 'be780c46e420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disponibles', sa.Integer(), nullable=True))
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('disponibles')

    # ### end Alembic commands ###
