"""add tipo_comprobante to factura

Revision ID: d9489f4bf651
Revises: 2319efa6207a
Create Date: 2026-03-01 20:24:19.731668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9489f4bf651'
down_revision = '2319efa6207a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa_fiscal_config', schema=None) as batch_op:
        batch_op.alter_column('pfx_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_comprobante_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tipos_comprobante', ['tipo_comprobante_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipo_comprobante_id')

    with op.batch_alter_table('empresa_fiscal_config', schema=None) as batch_op:
        batch_op.alter_column('pfx_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
