"""Agregar campo recargo_tarjeta a ventas

Revision ID: dceba0004e6b
Revises: bddc6c2dce1b
Create Date: 2025-08-02 20:47:01.325293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dceba0004e6b'
down_revision = 'bddc6c2dce1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recargo_tarjeta', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('recargo_tarjeta')

    # ### end Alembic commands ###
