"""agregar datos de sucursal a puntos de venta

Revision ID: ddac13e83351
Revises: 90827fed111f
Create Date: 2026-03-06 10:03:26.720262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddac13e83351'
down_revision = '90827fed111f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puntos_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('direccion', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puntos_venta', schema=None) as batch_op:
        batch_op.drop_column('telefono')
        batch_op.drop_column('direccion')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
