"""crea tabla tipos_documento y relacion con cliente

Revision ID: e24339f055be
Revises: 377dc2829fa5
Create Date: 2026-03-01 22:34:24.601332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24339f055be'
down_revision = '377dc2829fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_documento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tipos_documento', ['tipo_documento_id'], ['id'])
        batch_op.drop_column('tipo_doc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_doc', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipo_documento_id')

    # ### end Alembic commands ###
