"""agregar datos de sucursal a puntos de venta

Revision ID: e35e7bcef2db
Revises: ddac13e83351
Create Date: 2026-03-06 10:46:56.489312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35e7bcef2db'
down_revision = 'ddac13e83351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puntos_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puntos_venta', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
