"""Agregar precio_costo a detalles_venta

Revision ID: ec5b99587a8a
Revises: dceba0004e6b
Create Date: 2025-12-18 22:55:04.719554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5b99587a8a'
down_revision = 'dceba0004e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_costo', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_venta', schema=None) as batch_op:
        batch_op.drop_column('precio_costo')

    # ### end Alembic commands ###
