"""hacer la cantidad de producto en detalles con decimales

Revision ID: f1658604f4c5
Revises: ec5b99587a8a
Create Date: 2026-01-08 13:02:33.248269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1658604f4c5'
down_revision = 'ec5b99587a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_venta', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_venta', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
